/**
 * Built-in Public Portal Variants
 * These are default templates that are NOT stored in the database
 * They are read from the local file system
 */

const PORTAL_VARIANTS = [
  {
    _id: 'builtin-default',
    id: 'default',
    name: 'Padrão (Sidebar Escura)',
    description: 'Layout clássico com sidebar escura à direita',
    templateType: 'variant',
    variantId: 'default',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    _id: 'builtin-minimal',
    id: 'minimal',
    name: 'Minimalista',
    description: 'Design limpo, sem sidebar fixa, tudo em coluna única',
    templateType: 'variant',
    variantId: 'minimal',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    _id: 'builtin-modern',
    id: 'modern',
    name: 'Moderno',
    description: 'Estilo mais atual, cores vibrantes, animações leves',
    templateType: 'variant',
    variantId: 'modern',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    _id: 'builtin-restaurant',
    id: 'restaurant',
    name: 'Restaurante',
    description: 'Design especializado para restaurantes, com foco em apresentação de cardápio e pedidos',
    templateType: 'variant',
    variantId: 'restaurant',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
    {
    _id: 'builtin-hairstyle',
    id: 'hairstyle',
    name: 'Estilo de Cabelo',
    description: 'Design especializado para salões de beleza, com foco em apresentação de serviços de cabelo',
    templateType: 'variant',
    variantId: 'hairstyle',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
    
    {
    _id: 'builtin-catering',
    id: 'catering',
    name: 'Catering',
    description: 'Design especializado para eventos de catering, com foco em apresentação de serviços e pacotes',
    templateType: 'variant',
    variantId: 'catering',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
      {
    _id: 'builtin-ecommerce',
    id: 'ecommerce',
    name: 'Ecommerce',
    description: 'Design especializado para lojas virtuais e catálogos de produtos',
    templateType: 'variant',
    variantId: 'ecommerce',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
    {
    _id: 'builtin-logistic',
    id: 'logistic',
    name: 'Logística',
    description: 'Design especializado para empresas de logística e transporte, com foco em apresentação de serviços e rastreamento de entregas',
    templateType: 'variant',
    variantId: 'logistic',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    _id: 'builtin-plans',
    id: 'plans',
    name: 'Subscrição',
    description: 'Design especializado para empresas de subscrição e assinaturas',
    templateType: 'variant',
    variantId: 'plans',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
    {
    _id: 'builtin-boutique',
    id: 'boutique',
    name: 'Loja Virtual',
    description: 'Design especializado para lojas virtuais e catálogos de produtos',
    templateType: 'variant',
    variantId: 'boutique',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
     {
    _id: 'builtin-bar',
    id: 'bar',
    name: 'Bar',
    description: 'Design especializado para bares e pubs, com foco em apresentação de cardápio de bebidas e eventos',
    templateType: 'variant',
    variantId: 'bar',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
     {
    _id: 'builtin-lawyer',
    id: 'lawyer',
    name: 'Advocacia',
    description: 'Design especializado para escritórios de advocacia, com foco em apresentação de serviços jurídicos e casos',
    templateType: 'variant',
    variantId: 'lawyer',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
     {
    _id: 'builtin-cosmetics',
    id: 'cosmetics',
    name: 'Cosméticos',
    description: 'Design especializado para lojas virtuais e catálogos de produtos de cosméticos',
    templateType: 'variant',
    variantId: 'cosmetics',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },

     {
    _id: 'builtin-takeaway',
    id: 'takeaway',
    name: 'Takeaway',
    description: 'Design especializado para lojas de takeaway e delivery, com foco em apresentação de cardápio e opções de pedido',
    templateType: 'variant',
    variantId: 'takeaway',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
       {
    _id: 'builtin-clinica',
    id: 'clinica',
    name: 'Clinica',
    description: 'Especifico para clinicas',
    templateType: 'variant',
    variantId: 'clinica',
    isBuiltIn: true,
    isPublic: true,
    isPaid: false,
    price: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  
  

];

module.exports = { PORTAL_VARIANTS };
